spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/yanlzhl/springcloud-config/
server:
    port: 1201